Repository Votebot/bot, pull requests merged in 2019-12, with the labels that each got.

#11 Make shard and shardManager jars executable (Fix #9)
  shard/build.gradle.kts
  shardManager/build.gradle.kts
Labels: Enhancement

#17 Convert fluent getters to Kotlin getters (Fix #15)
  shardManager/src/main/kotlin/space/votebot/shardmanager/Application.kt
  shardManager/src/main/kotlin/space/votebot/shardmanager/config/Config.kt
Labels: Enhancement

#19 Migrate getters to Kotlin getters in shard config
  shard/src/main/kotlin/space/votebot/shard/Application.kt
  shard/src/main/kotlin/space/votebot/shard/config/Config.kt
Labels: Enhancement, Hold, Merge Ready

#20 Add Sentry properties in build
  shard/src/main/resources/sentry.properties
  shardManager/src/main/resources/sentry.properties
Labels: Hold, Merge Ready

#27 Replace SLF4J with kotlin-logging
  common/build.gradle.kts
Labels: Enhancement
